# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_UNIT_TESTS="yes"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"
    - RUN_PHPCS="yes"
    - RUN_UNIT_TESTS="no"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: 7.3
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no"
    - php: nightly
      env: INSTALL_APCU="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no"
  allow_failures:
    - php: 7.3
    - php: nightly

services:

before_script:
  - phpenv config-rm xdebug.ini
  # Make sure all dev dependencies are installed
  - composer install

script:
  - if [[ $RUN_PHPCS == "yes" ]]; then vendor/bin/phpcs --report=full --ignore=*/tests/*,*/data/*,*/vendor/*,*/tmpl/* --extensions=php -p --standard=vendor/joomla/coding-standards/Joomla .; fi
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then vendor/bin/phpunit --configuration travisci-phpunit.xml; fi

branches:
  except:
    - JBSM6.2
