language: php

sudo: false

php:
  - 5.3
# Until we start using phpunit we only need to test are menumum version.
#  - 5.4
#  - 5.5
#  - 5.6

services:
  - memcached
  - redis-server

before_script:
  - composer install --dev
  # - pyrus install -f pear/PHP_CodeSniffer-1.5.5
  # - pyrus install -f pear/Cache_Lite
  # - pear channel-discover pear.phing.info
  # - pear channel-discover pear.phpmd.org
  # - pear install phpmd/PHP_PMD
  # - pear install phing/phing
  - phpenv rehash
  # Set up Apache
  # - ./build/travis/php-apache.sh
  # Enable additional PHP extensions
  - phpenv config-add build/travis/phpenv/memcached.ini
  - phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini
  - phpenv config-add build/travis/phpenv/redis.ini

script:
  - bin/phing pmd
  - bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .

branches:
  except:
    - JBSM6.2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f8fe48fc801879e7535
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
