# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="yes"
    - RUN_UNIT_TESTS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true
  include:
    - php: 5.3
#    - php: 5.4
#    - php: 5.5
#    - php: 5.6
#    - php: 7.0

services:
  - memcache
  - memcached
  - redis-server

before_script:
  - phpenv config-rm xdebug.ini
  # Make sure all dev dependencies are installed
  - composer install

script:
  #- libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
  - if [[ $RUN_PHPCS == "yes" ]]; then bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .; fi
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi

branches:
  except:
    - JBSM6.2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f8fe48fc801879e7535
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
